//
// Created by ROW on 15.12.2015.
//

#ifndef INC_2DDYNAMICARRAY_BADBORDEREXCEPTION_H
#define INC_2DDYNAMICARRAY_BADBORDEREXCEPTION_H


class BadBorderException {

};


#endif //INC_2DDYNAMICARRAY_BADBORDEREXCEPTION_H
