//
// Created by awemath on 15.12.15.
//

#ifndef INC_2DDYNAMICARRAY_MEMORYLIMITEXCEDED_H
#define INC_2DDYNAMICARRAY_MEMORYLIMITEXCEDED_H


class MemoryLimitExceded {

};


#endif //INC_2DDYNAMICARRAY_MEMORYLIMITEXCEDED_H
